const {PrismaClient}=require("@prisma/client");const bcrypt=require("bcryptjs");const crypto=require("crypto");const {sign,requireAuth,requireRole}=require("../lib/auth");const {assertTransition,rewardForDelivery}=require("../lib/domain");const db=global.__earnDb||new PrismaClient();if(process.env.NODE_ENV!=="production")global.__earnDb=db;
const json=(res,status,data)=>{res.statusCode=status;res.setHeader("content-type","application/json");res.end(JSON.stringify(data,(_,v)=>typeof v==="bigint"?v.toString():v))};const body=async req=>{if(req.body)return req.body;let s="";for await(const c of req)s+=c;if(s.length>1e6)throw Object.assign(new Error("Payload too large"),{status:413});return s?JSON.parse(s):{}};const path=req=>new URL(req.url,"http://x").pathname.replace(/^\/api/,"");const normalizePhone=p=>{let x=String(p||"").replace(/\D/g,"");if(x.startsWith("977"))x=x.slice(3);if(x.length!==10||!/^9[78]/.test(x))throw Object.assign(new Error("Enter a valid Nepal mobile number"),{status:400});return x};const hashPhone=p=>crypto.createHash("sha256").update(normalizePhone(p)).digest("hex");
module.exports=async(req,res)=>{try{const p=path(req),m=req.method;
if(m==="POST"&&p==="/auth/signup"){const b=await body(req);const phone=normalizePhone(b.phone),password=String(b.password||""),role=String(b.role||"");if(password.length<8)return json(res,400,{error:"Password must be at least 8 characters"});if(!["EARNER","BUSINESS"].includes(role))return json(res,400,{error:"Choose earner or business"});const name=String(b.name||"").trim();if(name.length<2||name.length>80)return json(res,400,{error:"Enter your name"});const businessName=String(b.businessName||"").trim();if(role==="BUSINESS"&&(businessName.length<2||businessName.length>80))return json(res,400,{error:"Enter your business name"});if(await db.user.findUnique({where:{phone}}))return json(res,409,{error:"An account already exists for this phone"});const passwordHash=await bcrypt.hash(password,12);const u=await db.$transaction(async tx=>{const user=await tx.user.create({data:{phone,passwordHash,role}});if(role==="EARNER")await tx.earnerProfile.create({data:{userId:user.id,displayName:name}});else await tx.business.create({data:{ownerId:user.id,name:businessName,verified:false}});return user});return json(res,201,{token:sign(u),role:u.role});}
if(m==="POST"&&p==="/auth/login"){const b=await body(req);let phone;try{phone=normalizePhone(b.phone)}catch{return json(res,401,{error:"Invalid credentials"})}const u=await db.user.findUnique({where:{phone}});if(!u||!await bcrypt.compare(b.password||"",u.passwordHash))return json(res,401,{error:"Invalid credentials"});return json(res,200,{token:sign(u),role:u.role});}
if(m==="GET"&&p==="/campaigns"){const rows=await db.campaign.findMany({where:{status:"LIVE"},include:{business:{select:{name:true,verified:true}}},orderBy:{createdAt:"desc"}});return json(res,200,rows);}
const session=requireAuth(req);
if(m==="GET"&&p==="/me"){const u=await db.user.findUnique({where:{id:session.sub},select:{id:true,phone:true,role:true,earner:{select:{displayName:true}},business:{select:{name:true,verified:true}}}});if(!u)return json(res,404,{error:"Account not found"});return json(res,200,u);}
if(m==="POST"&&p==="/campaigns"){requireRole(session,"BUSINESS");const b=await body(req),biz=await db.business.findUnique({where:{ownerId:session.sub}});if(!biz)return json(res,409,{error:"Business profile required"});const row=await db.campaign.create({data:{businessId:biz.id,type:b.type,title:b.title,city:b.city,rewardPaisa:BigInt(Math.round(Number(b.rewardNpr)*100)),cap:Number(b.cap),successRule:b.successRule,status:"DRAFT"}});return json(res,201,row);}
const pub=p.match(/^\/campaigns\/([^/]+)\/publish$/);if(m==="POST"&&pub){requireRole(session,"BUSINESS","ADMIN");const c=await db.campaign.findUnique({where:{id:pub[1]},include:{business:true}});if(!c)return json(res,404,{error:"Campaign not found"});if(session.role!=="ADMIN"&&c.business.ownerId!==session.sub)return json(res,403,{error:"Forbidden"});return json(res,200,await db.campaign.update({where:{id:c.id},data:{status:"LIVE"}}));}
const start=p.match(/^\/campaigns\/([^/]+)\/start$/);if(m==="POST"&&start){requireRole(session,"EARNER");const c=await db.campaign.findFirst({where:{id:start[1],status:"LIVE"}});if(!c)return json(res,404,{error:"Live campaign not found"});const code=crypto.randomBytes(5).toString("hex");const a=await db.attribution.upsert({where:{campaignId_earnerId:{campaignId:c.id,earnerId:session.sub}},create:{campaignId:c.id,earnerId:session.sub,code},update:{}});return json(res,200,a);}
if(m==="POST"&&p==="/orders"){requireRole(session,"EARNER");const b=await body(req);if(!b.idempotencyKey)return json(res,400,{error:"idempotencyKey required"});const a=await db.attribution.findUnique({where:{code:b.attributionCode}});if(!a||a.earnerId!==session.sub)return json(res,400,{error:"Invalid attribution"});const c=await db.campaign.findFirst({where:{id:a.campaignId,status:"LIVE",type:"ORDER"}});if(!c)return json(res,409,{error:"Order campaign unavailable"});const biz=await db.business.findUnique({where:{id:c.businessId}});const existing=await db.order.findUnique({where:{idempotencyKey:b.idempotencyKey}});if(existing)return json(res,200,existing);const o=await db.order.create({data:{campaignId:c.id,businessId:biz.id,earnerId:session.sub,attributionCode:a.code,customerName:b.customerName,customerPhoneHash:hashPhone(b.customerPhone),product:b.product,quantity:Number(b.quantity||1),idempotencyKey:b.idempotencyKey}});return json(res,201,o);}
const tr=p.match(/^\/orders\/([^/]+)\/(accept|deliver|cancel)$/);if(m==="POST"&&tr){requireRole(session,"BUSINESS","ADMIN");const desired={accept:"ACCEPTED",deliver:"DELIVERED",cancel:"CANCELLED"}[tr[2]];const result=await db.$transaction(async tx=>{const o=await tx.order.findUnique({where:{id:tr[1]},include:{campaign:true,business:true}});if(!o)throw Object.assign(new Error("Order not found"),{status:404});if(session.role!=="ADMIN"&&o.business.ownerId!==session.sub)throw Object.assign(new Error("Forbidden"),{status:403});if(o.status===desired)return o;assertTransition(o.status,desired);if(desired!=="DELIVERED")return tx.order.update({where:{id:o.id},data:{status:desired}});const spec=rewardForDelivery(o,o.campaign);const count=await tx.reward.count({where:{order:{campaignId:o.campaignId},status:{in:["EARNED","PAYABLE","PAID"]}}});if(count>=o.campaign.cap)throw Object.assign(new Error("Campaign reward cap reached"),{status:409});await tx.order.update({where:{id:o.id},data:{status:"DELIVERED"}});await tx.reward.create({data:{orderId:o.id,userId:o.earnerId,amountPaisa:spec.amountPaisa,status:"EARNED"}});await tx.ledgerEntry.create({data:{userId:o.earnerId,kind:"REWARD_EARNED",amountPaisa:spec.amountPaisa,referenceType:"ORDER",referenceId:o.id,idempotencyKey:spec.ledgerKey}});return tx.order.findUnique({where:{id:o.id},include:{reward:true}})});return json(res,200,result);}
if(m==="GET"&&p==="/me/orders"){requireRole(session,"EARNER");const rows=await db.order.findMany({where:{earnerId:session.sub},include:{campaign:{select:{title:true,rewardPaisa:true}},reward:true},orderBy:{createdAt:"desc"}});return json(res,200,rows);}
if(m==="GET"&&p==="/business/orders"){requireRole(session,"BUSINESS");const biz=await db.business.findUnique({where:{ownerId:session.sub}});if(!biz)return json(res,409,{error:"Business profile required"});const rows=await db.order.findMany({where:{businessId:biz.id},include:{campaign:{select:{title:true,rewardPaisa:true}}},orderBy:{createdAt:"desc"}});return json(res,200,rows);}
if(m==="GET"&&p==="/business/campaigns"){requireRole(session,"BUSINESS");const biz=await db.business.findUnique({where:{ownerId:session.sub}});if(!biz)return json(res,409,{error:"Business profile required"});return json(res,200,await db.campaign.findMany({where:{businessId:biz.id},orderBy:{createdAt:"desc"}}));}
if(m==="GET"&&p==="/me/earnings"){requireRole(session,"EARNER");const entries=await db.ledgerEntry.findMany({where:{userId:session.sub},orderBy:{createdAt:"desc"}});const total=entries.reduce((n,e)=>n+e.amountPaisa,0n);return json(res,200,{balancePaisa:total,entries});}
return json(res,404,{error:"Not found"});}catch(e){console.error(e);return json(res,e.status||500,{error:e.status?e.message:"Internal server error"});}};