const {PrismaClient}=require("@prisma/client");const bcrypt=require("bcryptjs");const crypto=require("crypto");const {sign,requireAuth,requireRole}=require("../lib/auth");const {assertTransition,rewardForDelivery}=require("../lib/domain");const db=global.__earnDb||new PrismaClient();if(process.env.NODE_ENV!=="production")global.__earnDb=db;
const json=(res,status,data)=>{res.statusCode=status;res.setHeader("content-type","application/json");res.end(JSON.stringify(data,(_,v)=>typeof v==="bigint"?v.toString():v))};const body=async req=>{if(req.body)return req.body;let s="";for await(const c of req)s+=c;if(s.length>1e6)throw Object.assign(new Error("Payload too large"),{status:413});return s?JSON.parse(s):{}};const path=req=>new URL(req.url,"http://x").pathname.replace(/^\/api/,"");const hashPhone=p=>crypto.createHash("sha256").update(String(p).replace(/\D/g,"")).digest("hex");
module.exports=async(req,res)=>{try{const p=path(req),m=req.method;if(m==="POST"&&p==="/auth/login"){const b=await body(req),u=await db.user.findUnique({where:{phone:b.phone}});if(!u||!await bcrypt.compare(b.password||"",u.passwordHash))return json(res,401,{error:"Invalid credentials"});return json(res,200,{token:sign(u),role:u.role});}
if(m==="GET"&&p==="/campaigns"){const rows=await db.campaign.findMany({where:{status:"LIVE"},include:{business:{select:{name:true,verified:true}}},orderBy:{createdAt:"desc"}});return json(res,200,rows);}
const session=requireAuth(req);
if(m==="POST"&&p==="/campaigns"){requireRole(session,"BUSINESS");const b=await body(req),biz=await db.business.findUnique({where:{ownerId:session.sub}});if(!biz)return json(res,409,{error:"Business profile required"});const row=await db.campaign.create({data:{businessId:biz.id,type:b.type,title:b.title,city:b.city,rewardPaisa:BigInt(Math.round(Number(b.rewardNpr)*100)),cap:Number(b.cap),successRule:b.successRule,status:"DRAFT"}});return json(res,201,row);}
const pub=p.match(/^\/campaigns\/([^/]+)\/publish$/);if(m==="POST"&&pub){requireRole(session,"BUSINESS","ADMIN");const c=await db.campaign.findUnique({where:{id:pub[1]},include:{business:true}});if(!c)return json(res,404,{error:"Campaign not found"});if(session.role!=="ADMIN"&&c.business.ownerId!==session.sub)return json(res,403,{error:"Forbidden"});return json(res,200,await db.campaign.update({where:{id:c.id},data:{status:"LIVE"}}));}
const start=p.match(/^\/campaigns\/([^/]+)\/start$/);if(m==="POST"&&start){requireRole(session,"EARNER");const c=await db.campaign.findFirst({where:{id:start[1],status:"LIVE"}});if(!c)return json(res,404,{error:"Live campaign not found"});const code=crypto.randomBytes(5).toString("hex");const a=await db.attribution.upsert({where:{campaignId_earnerId:{campaignId:c.id,earnerId:session.sub}},create:{campaignId:c.id,earnerId:session.sub,code},update:{}});return json(res,200,a);}
if(m==="POST"&&p==="/orders"){requireRole(session,"EARNER");const b=await body(req);if(!b.idempotencyKey)return json(res,400,{error:"idempotencyKey required"});const a=await db.attribution.findUnique({where:{code:b.attributionCode}});if(!a||a.earnerId!==session.sub)return json(res,400,{error:"Invalid attribution"});const c=await db.campaign.findFirst({where:{id:a.campaignId,status:"LIVE",type:"ORDER"}});if(!c)return json(res,409,{error:"Order campaign unavailable"});const biz=await db.business.findUnique({where:{id:c.businessId}});const existing=await db.order.findUnique({where:{idempotencyKey:b.idempotencyKey}});if(existing)return json(res,200,existing);const o=await db.order.create({data:{campaignId:c.id,businessId:biz.id,earnerId:session.sub,attributionCode:a.code,customerName:b.customerName,customerPhoneHash:hashPhone(b.customerPhone),product:b.product,quantity:Number(b.quantity||1),idempotencyKey:b.idempotencyKey}});return json(res,201,o);}
const tr=p.match(/^\/orders\/([^/]+)\/(accept|deliver|cancel)$/);if(m==="POST"&&tr){requireRole(session,"BUSINESS","ADMIN");const desired={accept:"ACCEPTED",deliver:"DELIVERED",cancel:"CANCELLED"}[tr[2]];const result=await db.$transaction(async tx=>{const o=await tx.order.findUnique({where:{id:tr[1]},include:{campaign:true,business:true}});if(!o)throw Object.assign(new Error("Order not found"),{status:404});if(session.role!=="ADMIN"&&o.business.ownerId!==session.sub)throw Object.assign(new Error("Forbidden"),{status:403});if(o.status===desired)return o;assertTransition(o.status,desired);if(desired!=="DELIVERED")return tx.order.update({where:{id:o.id},data:{status:desired}});const spec=rewardForDelivery(o,o.campaign);const count=await tx.reward.count({where:{order:{campaignId:o.campaignId},status:{in:["EARNED","PAYABLE","PAID"]}}});if(count>=o.campaign.cap)throw Object.assign(new Error("Campaign reward cap reached"),{status:409});await tx.order.update({where:{id:o.id},data:{status:"DELIVERED"}});await tx.reward.create({data:{orderId:o.id,userId:o.earnerId,amountPaisa:spec.amountPaisa,status:"EARNED"}});await tx.ledgerEntry.create({data:{userId:o.earnerId,kind:"REWARD_EARNED",amountPaisa:spec.amountPaisa,referenceType:"ORDER",referenceId:o.id,idempotencyKey:spec.ledgerKey}});return tx.order.findUnique({where:{id:o.id},include:{reward:true}})});return json(res,200,result);}
if(m==="GET"&&p==="/me/earnings"){requireRole(session,"EARNER");const entries=await db.ledgerEntry.findMany({where:{userId:session.sub},orderBy:{createdAt:"desc"}});const total=entries.reduce((n,e)=>n+e.amountPaisa,0n);return json(res,200,{balancePaisa:total,entries});}
return json(res,404,{error:"Not found"});}catch(e){console.error(e);return json(res,e.status||500,{error:e.status?e.message:"Internal server error"});}};